import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';

const scene = new THREE.Scene();
scene.background = new THREE.Color(0xffffff);

// Camera for 9:16 vertical orientation
const container = document.getElementById('canvas-container');
const camera = new THREE.PerspectiveCamera(45, container.clientWidth / container.clientHeight, 0.1, 100);
camera.position.set(0, 1.5, 4);

const canvas = document.querySelector('#canvas3d');
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: false });
renderer.setSize(container.clientWidth, container.clientHeight);
renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));

// Realistic Shadows & Lighting
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1.0;

// Ambient Fill (Base visibility) 
const ambientLight = new THREE.AmbientLight(0xffffff, 0.4);
scene.add(ambientLight);

// 1. Key Light (Main softbox simulating studio light)
const keyLight = new THREE.DirectionalLight(0xffffff, 1.8);
keyLight.position.set(3, 5, 5); // Front-Right high
keyLight.castShadow = true;
// High-res tight shadows bounding the character footprint
keyLight.shadow.mapSize.width = 2048;
keyLight.shadow.mapSize.height = 2048;
keyLight.shadow.camera.near = 0.5;
keyLight.shadow.camera.far = 15;
keyLight.shadow.camera.left = -1.5;
keyLight.shadow.camera.right = 1.5;
keyLight.shadow.camera.top = 1.5;
keyLight.shadow.camera.bottom = -1.5;
keyLight.shadow.bias = -0.0001; 
keyLight.shadow.radius = 4; // Soften the shadow edges simulating a softbox
scene.add(keyLight);

// 2. Fill Light (Opposite side to soften harsh key shadows so details aren't lost)
const fillLight = new THREE.DirectionalLight(0xebebeb, 1.0);
fillLight.position.set(-4, 3, 2); // Front-Left low
scene.add(fillLight);

// 3. Rim Light (Backlight pointing at camera to create the "halo" edge, separating to make it pop holographically)
const rimLight = new THREE.SpotLight(0xffffff, 3.5);
rimLight.position.set(0, 4, -5); // Behind subject, high
rimLight.angle = Math.PI / 4; 
rimLight.penumbra = 0.8; 
rimLight.decay = 1.5;
scene.add(rimLight);

// Ground Plane for Shadows
const planeGeo = new THREE.PlaneGeometry(20, 20);
const planeMat = new THREE.ShadowMaterial({ opacity: 0.15 });
const plane = new THREE.Mesh(planeGeo, planeMat);
plane.rotation.x = -Math.PI / 2;
plane.receiveShadow = true;
scene.add(plane);

const controls = new OrbitControls(camera, renderer.domElement);
controls.enableDamping = true;
controls.dampingFactor = 0.05;
controls.target.set(0, 1, 0);

// Animation setup
let mixer;
let actions = {};
let activeAction;
let model;
const clock = new THREE.Clock();

const loader = new GLTFLoader();
const progressBar = document.getElementById('progress-bar');
const loadingText = document.getElementById('loading-text');

let loadedCount = 0;
const totalFiles = 4;

function updateProgress() {
    loadedCount++;
    const progress = (loadedCount / totalFiles) * 100;
    progressBar.style.width = progress + '%';
    if (loadedCount === totalFiles) {
        hideLoader();
    }
}

// Load Main Character
loadingText.innerText = "Character Base";
loader.load('Meshy_AI_biped/Meshy_AI_Character_output.glb', (gltf) => {
    model = gltf.scene;
    
    // Enable shadows for the model
    model.traverse((child) => {
        if (child.isMesh) {
            child.castShadow = true;
            child.receiveShadow = true;
        }
    });

    scene.add(model);
    mixer = new THREE.AnimationMixer(model);
    
    // Extract base idle animation from the character file itself if present
    if (gltf.animations && gltf.animations.length > 0) {
        actions['Idle'] = mixer.clipAction(gltf.animations[0]);
        activeAction = actions['Idle'];
        activeAction.play();
    }
    
    updateProgress();

    // Load Animations separately
    loadAnimation('Walking', 'Meshy_AI_biped/Meshy_AI_Animation_Walking_withSkin.glb');
    loadAnimation('Running', 'Meshy_AI_biped/Meshy_AI_Animation_Running_withSkin.glb');
    loadAnimation('Crouch', 'Meshy_AI_biped/Meshy_AI_Animation_Female_Crouch_Pick_Up_Place_Side_withSkin.glb');
});

function loadAnimation(name, url) {
    loader.load(url, (gltf) => {
        const animation = gltf.animations[0];
        if (animation) {
            // Check if animation track names need to be adapted. Usually if they are generated by the same tool, they match.
            const action = mixer.clipAction(animation);
            actions[name] = action;
        } else {
            console.warn(`No animation found in ${url}`);
        }
        updateProgress();
    });
}

function hideLoader() {
    const loaderDiv = document.getElementById('loader');
    loaderDiv.style.opacity = '0';
    setTimeout(() => {
        loaderDiv.style.display = 'none';
    }, 800);
}

// Action transition function
function fadeToAction(name, duration = 0.5) {
    const previousAction = activeAction;
    activeAction = actions[name];

    // Update active button state
    document.querySelectorAll('.action-btn').forEach(btn => {
        btn.classList.remove('active');
        if (btn.dataset.action === name) btn.classList.add('active');
    });
    
    // Update the top label UI to show the current animation name
    const animNameLabel = document.getElementById('anim-name');
    if(animNameLabel) animNameLabel.innerText = name;

    if (name === 'Idle' || !activeAction) {
        if (previousAction) {
            previousAction.fadeOut(duration);
        }
        activeAction = null;
        return;
    }

    if (previousAction !== activeAction) {
        activeAction.reset().setEffectiveTimeScale(1).setEffectiveWeight(1).fadeIn(duration).play();
        if (previousAction) {
            previousAction.fadeOut(duration);
        }
    }
}

// Button Events
document.querySelectorAll('.action-btn').forEach(btn => {
    btn.addEventListener('click', (e) => {
        // Use currentTarget to ensure we always get the button's data attribute, 
        // not the child <span> that was clicked.
        const actionName = e.currentTarget.dataset.action;
        if(actionName) {
            fadeToAction(actionName);
            updateVoiceStatus(`Action: ${actionName}`);
        }
    });
});

// Voice Implementation
const voiceBtn = document.getElementById('voice-orb');
const voiceStatus = document.getElementById('transcript-text');

function updateVoiceStatus(text) {
    voiceStatus.innerText = text;
    voiceStatus.classList.add('visible');
}

if ('webkitSpeechRecognition' in window || 'SpeechRecognition' in window) {
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
    const recognition = new SpeechRecognition();
    recognition.continuous = true;
    recognition.interimResults = false;
    recognition.lang = 'en-US';

    let isListening = false;

    voiceBtn.addEventListener('click', () => {
        if (isListening) {
            recognition.stop();
        } else {
            try {
                recognition.start();
            } catch (e) {
                console.log('Recognition already started');
            }
        }
    });

    recognition.onstart = () => {
        isListening = true;
        voiceBtn.classList.add('listening');
        // We removed the inner span modifying logic, as the orb is purely SVG
        updateVoiceStatus('Listening... Say "Walk", "Run", or "Crouch"');
    };

    recognition.onresult = (event) => {
        const lastResultIndex = event.results.length - 1;
        const command = event.results[lastResultIndex][0].transcript.toLowerCase().trim();
        
        console.log('Voice command received:', command);

        if (command.includes('walk')) {
            fadeToAction('Walking');
            updateVoiceStatus('Walking');
        } else if (command.includes('run')) {
            fadeToAction('Running');
            updateVoiceStatus('Running');
        } else if (command.includes('crouch') || command.includes('pick') || command.includes('down')) {
            fadeToAction('Crouch');
            updateVoiceStatus('Crouch');
        } else if (command.includes('stop') || command.includes('idle')) {
            fadeToAction('Idle');
            updateVoiceStatus('Idle');
        } else {
            updateVoiceStatus(`Unrecognized: "${command}"`);
        }
    };

    recognition.onerror = (event) => {
        console.error('Speech recognition error', event.error);
        updateVoiceStatus(`Error: ${event.error}`);
        isListening = false;
        voiceBtn.classList.remove('listening');
    };

    recognition.onend = () => {
        isListening = false;
        voiceBtn.classList.remove('listening');
    };
} else {
    voiceBtn.addEventListener('click', () => {
        alert('Speech recognition is not supported in this browser. Please use Chrome or a supported browser.');
    });
}

// Window Resize Handling
window.addEventListener('resize', () => {
    const container = document.getElementById('canvas-container');
    camera.aspect = container.clientWidth / container.clientHeight;
    camera.updateProjectionMatrix();
    renderer.setSize(container.clientWidth, container.clientHeight);
});

// Render Loop
const animate = () => {
    requestAnimationFrame(animate);
    const delta = clock.getDelta();
    if (mixer) mixer.update(delta);
    controls.update();
    renderer.render(scene, camera);
};
animate();
